language: ruby
sudo: false

rvm:
  - 2.1.0

notifications:
  irc:
    channels:
      - "irc.freenode.net#crowbar"
    template:
      - "%{repository_slug} (%{commit}) : %{message} by %{author}"
      - "You can see the details at %{build_url}"
    on_success: change
    on_failure: always
